
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: check-json
    exclude: .evergreen/atlas_data_lake/test.driverdata.json
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace
  - id: check-executables-have-shebangs

# We use the Python version instead of the original version which seems to require Docker
# https://github.com/koalaman/shellcheck-precommit
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
    - id: shellcheck
      name: shellcheck
      args: ["--severity=error"]

- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.27.0
  hooks:
    - id: check-jsonschema
      name: "Check GitHub Workflows"
      files: ^\.github/workflows/
      types: [yaml]
      args: ["--schemafile", "https://json.schemastore.org/github-workflow"]

- repo: https://github.com/codespell-project/codespell
  rev: "v2.2.6"
  hooks:
  - id: codespell
    exclude: |
        (?x)(
          .evergreen/github_app/package-lock.json|
          .evergreen/csfle/bottle.py|
          .pem$
        )
    args: ["-L", "fle,aks"]

- repo: local
  hooks:
  - id: executable-shell
    name: executable-shell
    entry: chmod +x
    language: system
    types: [shell]
